### ISSUE TITLE
can't run main/py

### ISSUE THREAD

**Issue by m3m3-chan** [tuomastik/video_face_detection#1]
Hi 
thank you for this work! 
I want to run main.py but it gives `No module named 'wide_resnet'` error. I am assuming I am missing the wide_resnet file .. so where to get it? 

thanks,

**Comment by tuomastik** [comment]
Hello and thank you! The issue is that `wide_resnet.py` is not found, which is expected to be in a folder `age-gender-estimation` that is expected to be located under the root of this repository. That file and folder are automatically pulled from GitHub as part of a git submodule if you clone this repository using `--recursive` flag, which forces git to clone all defined submodules in the repository. `README.md` of this repository instructs to use that command. If you didn't use the `--recursive` flag, please run the following to get the submodule and try to run `main.py` again:
```bash
git submodule init
git submodule update
```
If you did clone this repository using the `--recursive` flag, please make sure that Python working directory is the repository root when executing `main.py`.
